<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="UziMac.home" name="myTest" tests="22" failures="7" timestamp="23 Dec 2015 18:16:15 GMT" time="326.898" errors="0">
  <testcase name="testDevices" time="57.654" classname="test.java.NativeExe"/>
  <testcase name="testDevices" time="0.569" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:134)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="58.544" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:134)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="58.826" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:134)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="62.614" classname="test.java.NativeExe"/>
  <testcase name="testDevices" time="63.273" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:134)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="64.322" classname="test.java.NativeExe"/>
  <testcase name="testDevices" time="68.137" classname="test.java.NativeExe"/>
  <testcase name="testDevices" time="79.221" classname="test.java.NativeExe"/>
  <testcase name="testDevices" time="70.005" classname="test.java.NativeExe"/>
  <testcase name="testDevices" time="129.057" classname="test.java.NativeExe"/>
  <testcase name="testDevices" time="130.833" classname="test.java.NativeExe"/>
  <testcase name="testDevices" time="95.616" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:134)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="123.555" classname="test.java.NativeExe"/>
  <testcase name="testDevices" time="62.694" classname="test.java.NativeExe"/>
  <testcase name="testDevices" time="130.197" classname="test.java.NativeExe"/>
  <testcase name="testDevices" time="116.39" classname="test.java.NativeExe"/>
  <testcase name="testDevices" time="130.794" classname="test.java.NativeExe"/>
  <testcase name="testDevices" time="138.955" classname="test.java.NativeExe"/>
  <testcase name="testDevices" time="74.579" classname="test.java.NativeExe"/>
  <testcase name="testDevices" time="163.921" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:134)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="198.055" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:134)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
</testsuite> <!-- myTest -->
