<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="UziMac.local" name="myTest" tests="136" failures="91" timestamp="28 Dec 2015 22:05:04 GMT" time="1051.565" errors="0">
  <testcase name="testDevices" time="1.431" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="1.432" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="1.461" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="58.333" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="61.395" classname="test.java.NativeExe"/>
  <testcase name="testDevices" time="0.584" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="72.458" classname="test.java.NativeExe"/>
  <testcase name="testDevices" time="73.245" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="71.945" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="77.432" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="81.674" classname="test.java.NativeExe"/>
  <testcase name="testDevices" time="0.368" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="99.095" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="42.598" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="57.902" classname="test.java.NativeExe"/>
  <testcase name="testDevices" time="0.59" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="70.798" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="156.97" classname="test.java.NativeExe"/>
  <testcase name="testDevices" time="43.272" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="87.891" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="83.721" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="90.207" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="183.305" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="134.727" classname="test.java.NativeExe"/>
  <testcase name="testDevices" time="76.37" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="48.526" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="0.553" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="76.117" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="72.884" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="0.623" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="138.878" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="94.239" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="84.471" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="72.488" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="98.499" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="47.083" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="121.25" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="90.314" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="70.902" classname="test.java.NativeExe"/>
  <testcase name="testDevices" time="64.211" classname="test.java.NativeExe"/>
  <testcase name="testDevices" time="75.319" classname="test.java.NativeExe"/>
  <testcase name="testDevices" time="64.395" classname="test.java.NativeExe"/>
  <testcase name="testDevices" time="100.923" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="45.152" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="0.506" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="73.535" classname="test.java.NativeExe"/>
  <testcase name="testDevices" time="98.179" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="91.089" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="0.494" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="74.619" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="154.759" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="90.509" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="37.309" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="70.987" classname="test.java.NativeExe"/>
  <testcase name="testDevices" time="123.223" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="70.816" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="92.704" classname="test.java.NativeExe"/>
  <testcase name="testDevices" time="84.463" classname="test.java.NativeExe"/>
  <testcase name="testDevices" time="92.893" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="58.312" classname="test.java.NativeExe"/>
  <testcase name="testDevices" time="67.278" classname="test.java.NativeExe"/>
  <testcase name="testDevices" time="67.873" classname="test.java.NativeExe"/>
  <testcase name="testDevices" time="99.228" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="101.694" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="57.036" classname="test.java.NativeExe"/>
  <testcase name="testDevices" time="62.31" classname="test.java.NativeExe"/>
  <testcase name="testDevices" time="86.65" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="0.579" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="76.56" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="195.599" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="47.256" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="89.46" classname="test.java.NativeExe"/>
  <testcase name="testDevices" time="0.551" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="99.374" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="182.675" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="50.026" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="0.61" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="75.434" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="0.535" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="52.645" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="54.814" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="107.682" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="69.061" classname="test.java.NativeExe"/>
  <testcase name="testDevices" time="73.645" classname="test.java.NativeExe"/>
  <testcase name="testDevices" time="64.694" classname="test.java.NativeExe"/>
  <testcase name="testDevices" time="82.529" classname="test.java.NativeExe"/>
  <testcase name="testDevices" time="65.368" classname="test.java.NativeExe"/>
  <testcase name="testDevices" time="129.664" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="138.407" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="0.541" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="95.663" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="82.345" classname="test.java.NativeExe"/>
  <testcase name="testDevices" time="99.13" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="70.949" classname="test.java.NativeExe"/>
  <testcase name="testDevices" time="74.695" classname="test.java.NativeExe"/>
  <testcase name="testDevices" time="61.607" classname="test.java.NativeExe"/>
  <testcase name="testDevices" time="83.249" classname="test.java.NativeExe"/>
  <testcase name="testDevices" time="58.027" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="88.131" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="94.572" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="72.563" classname="test.java.NativeExe"/>
  <testcase name="testDevices" time="69.651" classname="test.java.NativeExe"/>
  <testcase name="testDevices" time="62.369" classname="test.java.NativeExe"/>
  <testcase name="testDevices" time="68.568" classname="test.java.NativeExe"/>
  <testcase name="testDevices" time="76.093" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="0.485" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="79.671" classname="test.java.NativeExe"/>
  <testcase name="testDevices" time="67.62" classname="test.java.NativeExe"/>
  <testcase name="testDevices" time="75.937" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="54.021" classname="test.java.NativeExe"/>
  <testcase name="testDevices" time="143.616" classname="test.java.NativeExe"/>
  <testcase name="testDevices" time="145.751" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="0.517" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="54.275" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="79.777" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="104.584" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="61.453" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="62.767" classname="test.java.NativeExe"/>
  <testcase name="testDevices" time="68.493" classname="test.java.NativeExe"/>
  <testcase name="testDevices" time="78.682" classname="test.java.NativeExe"/>
  <testcase name="testDevices" time="60.418" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="129.808" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="70.553" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="86.063" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="40.249" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="81.157" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="85.789" classname="test.java.NativeExe"/>
  <testcase name="testDevices" time="75.702" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="62.544" classname="test.java.NativeExe"/>
  <testcase name="testDevices" time="57.141" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="83.673" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="82.964" classname="test.java.NativeExe"/>
  <testcase name="testDevices" time="83.226" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="81.163" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="74.427" classname="test.java.NativeExe">
    <failure type="java.lang.AssertionError" message="Test Ended with error">
      <![CDATA[java.lang.AssertionError: Test Ended with error
	at test.java.NativeExe.testDevices(NativeExe.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testDevices -->
  <testcase name="testDevices" time="151.835" classname="test.java.NativeExe"/>
</testsuite> <!-- myTest -->
